### ISSUE TITLE
Fix godep workspace problem in Travis

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/shield#146]
Travis is saying this:

```
$ godep restore

godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
```

We shouldn't have a `Godeps/_workspace` any more, right?

**Comment by geofffranks** [comment]
Did some investigation, and as best I can telll, this is a result of how travis is auto-restoring deps for us via godep.  We're not calling it directly, the magical travis godep restore is doing it, because we don't have a Godeps/_workspace directory. This will likely go away when travis gets updated with a recent godep version, or to handle the vendoring project that is now enabled-by-default.
