### ISSUE TITLE
Mysql as a back database for SHIELD

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield#184]
Greeting, 
Longterm we would like to have the alternative to use mysql as database. It will simplify the setup/deployments given most of our services are running on mysql (nevertheless with bosh this is not a problem). Anyway, long story sort,  this can be an external requirement we will need to handle.

Currently SHIELD support PostgreSQL, and SQLite. In the code, I saw that you are using directly SQL queries, therefore due to semantics (uuid, $1 bindvars) mysql cannot be supported out of the box.
A future work which will refactor the database interaction part using a framework like
https://github.com/go-gorp/gorp
https://github.com/jmoiron/sqlx
https://github.com/jinzhu/gorm
in order to make SHIELD  database agnostic would be something that you would like to see/work on?

Thx

**Comment by jhunt** [comment]
SHIELD only supports PostgreSQL as a database backend.   We utilize SQLite to avoid requiring a spinning PostgreSQL process while doing tests, but do not support (nor recommend) its use in real-world deployments.

Refactoring the (currently functional) database layer to support arbitrary database backends like MySQL, Oracle, or even MS SQL server brings additional complexity to the codebase for no real gain to the functionality of SHIELD itself.  To do this properly, we would then also need to modify the SHIELD BOSH release to allow selection of a database backend, as well as jobs for alternate backends (at least MySQL).

All of this added complexity brings with it additional support and testing overhead.  If we say we support MySQL as a backend (via an ORM or otherwise) we will need to vet the releases against both PostgreSQL and MySQL, doubling the work involved in a release.

Given that the current state (SHIELD using explicitly PostgreSQL) has no bearing on its ability to _back up_ MySQL target systems, I see little gain in reworking a perfectly functional (and well-tested) layer of the code.

Are you unable to use the `postgres` job that stands up a database inside the BOSH deployment?

**Comment by karampok** [comment]
Yes, i can understand that refactoring the database layer is a big task without obvious benefit to SHIELD itself. If we introduce changes, this should be only by picking up a good  ORM which will provide the abstraction in such extent that there will not be a need to validate SHIELD everytime against  different store backend (if possible of course). 

To your question, yes we will be unable to use postgres as defined in BOSH deployment. We will be required eventually  to use mysql db as back store, because all other  applications in our are setup are doing so.

Saying that, will you be willing to accept a pull request from our side  towards that direction?
Thanks!

**Comment by jhunt** [comment]
Understand completely.

We'll gladly review a pull request if you would like to submit it, but this level of change is going to necessitate some heavy scrutiny to ensure the continued quality of SHIELD.

What ORM were you planning to use?

**Comment by karampok** [comment]
great!
about which ORM we are planning to use. This is hard decision, because there is
not a perfect one in go and there is quite a lot of discussion on the topic without
a verdict . We are between gorm or sqlx, we do not consider gorp because it
doesn't seem to be maintained actively anymore.

Between, slqx and gorm, we have a preference in slqx. It seems simpler, it will
introduce less changes, since database/sql interface is a subset of sqlx, we
should not need a lot of changes of the db code which is important,  it supports
postgresql/boshlite/mysql and finally there are mostly positive commments.

Do you have any preference?

**Comment by jhunt** [comment]
We have not looked into available ORMs in Go, so I don't know that we have a preference.  If you think sqlx is preferable / more simple, I'd say go with that to start.

**Comment by karampok** [comment]
Hi, we have a first working version of SHIELD with mysql, there are still of course a lot of points to be discussed. It is tricky to support same time postgres and mysql, for example we need to have different sql schema.

In this repo/branch https://github.com/swisscom/shield/tree/mysql_support, we have our work.
Looking forward to your feedback. Let me know if you prefer to have PR to review better the changes.

Thx

**Comment by jhunt** [comment]
Is there any way to colocate the pg-specific and mysql-specific SQL statements in the same set of schema migration functions?

**Comment by karampok** [comment]
Probably yes, but i am not sure what do you mean, can you elaborate?
Do you suggest that we have only one set of statements for all dbs, and that are "reformated" one we make the the calls to the db? Thx

**Comment by jhunt** [comment]
I elaborated in #198

**Comment by gogolok** [comment]
Can be closed

**Comment by jhunt** [comment]
Thanks!
