### ISSUE TITLE
High Availability for SHIELD

### ISSUE THREAD

**Issue by karampok** [starkandwayne/shield#203]
Hi,
 this is a  longterm issue that we need to address in the next months.  As
you know, we have started using SHIELD for mysql backups.  We would like 
also to extend SHIELD for all services backup like mongodb, rabbitMQ, ELK etc. .
Nevertheless before we do that,  we need SHIELD to be  HA ready.
In other words, we need that the bosh release will spin up >2 instances of SHIELD that 
will run in different availability zones.

From my perspective the client-driven backups are HA ready, the
scheduling tasks are not, because only one instance should execute (or for
performance reasons task should be distributed among the intances).

Do you have a plan/design to that direction?

Thanks!

**Comment by gogolok** [comment]
If we do not want to introduce third-party dependencies, we could use database locks (atomic update statements) to lock/guard critical code sections.

The assumptions are then:
* HA database cluster
* clocks in sync
* atomic UPDATE SQL statements

The main event loop is in the supervisor#Run method.
https://github.com/starkandwayne/shield/blob/master/supervisor/supervisor.go#L261

We could use a global/big lock before doing any work (the 'select case' block), but this would lead to starvation or at least huge delays in the processing.

Rather than a big lock, we should use fine-grained locking for the 'case' blocks.

Is this approach something we should go on with? What do you think?

# Example

table: db_locks, rows: name, locked_at, locked_by

When there are archives to purge, we should first lock the database row with name `PURGE_ARCHIVE` via an UPDATE sql statement that sets the `locked_at` attribute/column to the current time. When we acquire that lock, we can proceed with the `s.PurgeArchives()` call. If we don't acquire the lock, we just go on with the next select case.

When the shieldd process dies, we should be able to retry our work immediately after the shieldd process came back (via monit for example). We could assign/generate a unique (uuid) instance name for every shieldd process, so it can take the lock `PURGE_ARCHIVE` when the `locked_by` name is the same as the assigned shieldd instance name.

When the shieldd process has acquired a lock, but dies forever, we could work with timeouts to allow to reenter a locked code section after for example 10 minutes.

```sql
UPDATE db_locks SET locked_at = NOW()
    WHERE name = 'PURGE_ARCHIVE' AND (locked_at IS NULL OR locked_at < '10 minutes ago')
```

We can unlock the critical code section by setting the `locked_by` and `locked_at` attributes/columns to `NULL` for the lock name `PUTGE_ARCHIVE`.

This idea is based on the delayed_job project.
https://github.com/collectiveidea/delayed_job_active_record/blob/master/lib/delayed/backend/active_record.rb#L89

**Comment by gogolok** [comment]
@jhunt @geofffranks Any thoughts on that topic?

**Comment by jhunt** [comment]
I still (personally) remain unconvinced that the cost/benefit of HA SHIELD is worth it at this moment.

**Comment by cweibel** [comment]
I would much rather have an easy way to simply restore SHIELD itself than all the complexities that are associated with clustering and HA.

Since your backups are usually stored on S3 or similar storage the worst you lose if the shield db is the configuration of the jobs/targets/etc and the association to the existing backup files.  Maybe have the shield db in a very particular bucket path or similar to make restore dead simple on which file to use?  My $0.02

**Comment by jhunt** [comment]
We have this: https://github.com/starkandwayne/shield/wiki/Recovering-from-a-Disaster-Using-SHIELD

**Comment by cweibel** [comment]
That is pretty much exactly what I was looking for. Thanks!!

**Comment by karampok** [comment]
Hi! 
Yes the HA is still relevant, and mainly because we work with [client-driven backups](https://github.com/starkandwayne/shield/issues/179).
So if SHIELD does not respond, then the temporary job will not be created, and user will see a 'failed' status. For the system-backups, it is less relevant.

It would be nice to evaluate the cost of having SHIELD HA, and if possible to have a design how to achieve HA. Since HA might be a requirement, we might be able to invest some resources to implement this feature. The design/general way of implementation should be approved by you in advance.

Best!
