### ISSUE TITLE
purge tasks remain in status pending

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield#210]
Purge tasks seem to get started regularly but always remain in pending status.

<img width="607" alt="screenshot 2016-10-10 11 32 36" src="https://cloud.githubusercontent.com/assets/8533296/19231967/5dfbddce-8edd-11e6-9c38-3ce1a1a4065c.png">

**Comment by jhunt** [comment]
I believe latest master may address this issue.  We had a bad SQL statement that got fixed in 5746cc6

Once #216 is reviewed / merged, we'll cut a new release and see if this is still a problem.

**Comment by jhunt** [comment]
Aha.  Found it.

This has been broken since fb2fcc59, a commit that introduced the "only run one job per target" behavior.  Except that purge tasks have no target, and are therefore _never_ runnable because of a SQL error (trying to use `""` as a UUID is bad juju in Postgres).

Will fix on master and hopefully cut a new SHIELD + BOSH release tomorrow with some more changes that are in-flight.
