### ISSUE TITLE
Invalid bucket name

### ISSUE THREAD

**Issue by tdeichel** [starkandwayne/shield#264]
Shield fails with "invalid bucket name" on any bucket name that starts with capital "R"

**Comment by thomasmmitchell** [comment]
I can shed a little light on this, but I'm not sure what to do with it quite yet

The minio library that is used for the s3 and scality plugin uses this regexp to match bucket names against: `^[a-z0-9][a-z0-9\.\-]{1,61}[a-z0-9]$`. If it doesn't match that, it's not "valid". Of note there is that there are _no_ capital letters allowed... at all.

The minio folks tend to stay rigid to the s3 spec. While Amazon technically allows capital letters in bucket names, they explicitly discourage it because the DNS spec is going to lowercase those letters for you. The minio folks seem to have taken that as a reason to not allow you to use uppercase letters. The source info that I'm sure those folks used as their spec when writing the library can be found here: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules

Technically, periods are also discouraged, but they allowed those(?)...

@jhunt Whatcha wanna do with it?

**Comment by jhunt** [comment]
Either we should run the verification inside the s3 plugin as part of plugin endpoint validation, or we should just be nice and lowercase the bucket names before passing them to the oh-so-picky minio lib.

@thomasmmitchell

**Comment by thomasmmitchell** [comment]
Minio will then stop complaining, but then it won't resolve to the bucket name when it makes a request because bucket names are case sensitive.

**Comment by jhunt** [comment]
So, validation it is!

**Comment by jhunt** [comment]
Just pushed `a138bac` to `v8` which resolves this with validation.
