### ISSUE TITLE
shied restore --raw is broken

### ISSUE THREAD

**Issue by bodymindarts** [starkandwayne/shield#268]
```
$ echo 1 | shield restore redis-default --raw
{"error":"Error 301 Moved Permanently"}
```

**Comment by thomasmmitchell** [comment]
I'm finally trying to cut through the CLI issue backlog. I know this was awhile back, but do you remember anything about the context of this bug? I'm not able to replicate it.

Are you sure this was related to restore at all? Awhile back, the boshrelease started using nginx to reroute requests to the daemon to a different port, and its possible you were on a version of the CLI that didn't want to follow a redirect (because Golang....). That's my hunch, anyway. There's never been anything in the restore code that would send back a 301. I'd just like to try and verify this hunch :)
