### ISSUE TITLE
As an operator I would like my target/store credentials to live in a credential manager

### ISSUE THREAD

**Issue by rkoster** [starkandwayne/shield#371]
Now that bosh and concourse have moved to storing credentials in credential managers (credhub / vault). It would be awesome if shield could move into this direction as well.
By looking up credentials from the credential manager at runtime it would be easier to rotate the credentials used for making backups.

**Comment by jhunt** [comment]
Can you elaborate?

**Comment by rkoster** [comment]
After taking some time to experiment with shield v8 I would like to reopen this issue.
Credhub support comes in 2 separate efforts:
- 1. Making the shield crypter backend configurable ([vault](https://github.com/starkandwayne/shield/blob/master/crypter/vault.go)/credhub).
- 2. Allowing variable lookup in plugin configuration. Similar to what BOSH and [Concourse](https://github.com/concourse/atc/tree/master/creds) have.

A configurable crypter backend would help with reducing the number of credential store systems to manage when running in a pcf envrionment. Since we could reuse the already deployed credhub.

Credential lookup in plugins would solve: https://github.com/starkandwayne/shield/pull/383, maybe we can even reuse some of the concourse atc code since they support lots of backends.

**Comment by jhunt** [comment]
I do not believe that moving credential lookup to the plugins would solve #383, since operators at the SHIELD Web UI and CLI still need to be able to review those credentials.  This was my main point of feedback on that PR -- unilaterally redacting all credentials everywhere makes it harder to validate a target configuration.  What that PR fails to provide is a nuanced access control set.
