### ISSUE TITLE
how to recovery SHIELD itself?

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield#413]
I install SHIELD using shield-boshrelease v8.0.8.

Can I get the latest guide how to recovery SHIELD itself?

Just backup and recovery /var/vcap/store/shield directory in shield vm?

The document [https://github.com/starkandwayne/shield/wiki/Recovering-from-a-Disaster-Using-SHIELD](https://github.com/starkandwayne/shield/wiki/Recovering-from-a-Disaster-Using-SHIELD) seems outdated.

**Comment by jhunt** [comment]
For the most part, yes.  That backs up the database and the vault.  You generally want to make that a "fixed key" backup, so that you don't need the vault to restore the vault (primacy problem).  On initialization of a new (replacement) SHIELD core, you will provide both the key and the backup archive to restore.

There are some nagging issues related to scheduling that occur after restore.  We're still working through those.

**Comment by jhunt** [comment]
I just put #415 in for the documentation work.
