### ISSUE TITLE
how to decompress backup archive?

### ISSUE THREAD

**Issue by eujungkim** [starkandwayne/shield#419]
I'm using v8.0.8 and try to upgrade v8.0.10.

In v8.0.8, I have downloaded some backup archives, decompress it by "tar -jxvf FILENAME" and check archives contents. (Additionally, I'm not using Fixed-Key Encryption to my backup.)

But in v8.0.10, when I try to decompress the backup archives, error like below occurs.

> tar: invalid magic
> tar: short read

Is the mechanism to compress backup archive changed?

How can I unpack the backup archive manually in v8.0.10?

**Comment by daviddob** [comment]
If you are **not** using fixed-key-backup then the key and iv used to encrypt the backup archive were randomly generated and stored by shield. In order to unpack an archive without fixed-key-backup it is a lengthly process to retrieve the correct keys from shield, manually decrypt, and then unpack. If this is a must and you still have access to the shield deployment that performed the backup I can try to assist you through the process. If you no longer have access to the deployment of shield that performed the backup, then they keys are inaccessible.

**Comment by eujungkim** [comment]
@daviddob If I use fixed key backup, is it possible to unpack backup archive manually?
If possible,  please explain detail howto.

**Comment by eujungkim** [comment]
@daviddob For not using fixed key backup, I still have access to the shield deployment that performed the backup, so please assist me through the process.
Additionally, about fixed key backup case, please explain the unpack process, too.
Thank you.

**Comment by daviddob** [comment]
Currently, the recommended way would be to restore the archive (potentially to a new target) via shield, to test the restore capability. The fixed key backup is used to backup and restore shield itself. When spinning up a new shield it will give you the opportunity to recover shield from a backup (and supply the fixed key), it will then restore shield and allow you to recover your archives from there once shield has been restored. To access archives manually without shield you'll have to decrypt the vault keys using the master password, retrieve the keys from there, then decrypt the archive, then unpack it. Ill have to write up some documentation and potentially a tool to make the process more streamlined when I have some free time.

**Comment by eujungkim** [comment]
Thank you for a kind explanation.
I look forward to seeing your documentation and tool  in the near future.
