### ISSUE TITLE
Demo broken (not building linux binaries) when running from macOS

### ISSUE THREAD

**Issue by nbari** [starkandwayne/shield#433]
When trying to run the demo within macOS, the binaries used in the docker container like `shieldd` are not cross-compiled therefore can't run within the Linux containers.

As an initial try I modified the `Makefile` with something like:

    demo: GOOS=linux GOARCH=amd64 
    demo: clean shield plugins
         ./demo/build
         (cd demo && docker-compose up)

But got this error from the outdated pagackge `shield/vendor/github.com/mattn/go-sqlite3` because of this in a second trie I removed the `vendor` dir in favor of using [go dep](https://golang.github.io/dep/), this time I was available to cross compile  `go-sqlite3`  but while trying to create a `Gopkg.[toml|lock]` files,  I stumble with the `plugin/swift`:

```
The following errors occurred while deducing packages:
  * "git.openstack.org/openstack/golang-client/openstack": unable to deduce repository and source type for "git.openstack.org/openstack/golang-client/openstack": unable to read metadata: go-import metadata not found

validateParams: could not deduce external imports' project roots
```

To continue, testing and simplify the contribuition process wondering is there is room to use `dep`? some code will need to be updated but the shiping process could be simplified/being more portable.

**Comment by jhunt** [comment]
Honestly, the demo is pretty badly broken on numerous fronts:

1) It has to be run from Linux (as you mentioned)
2) It leverages some external software that detracts from the demo experience
3) It was literally written to support a single video demo

We've got plans to replace the whole demo with a collection of purpose-built web systems that better showcase what SHIELD can do for things like PostgreSQL, Consul, MongoDB, etc.

The `vendor/` directory is still required, as you found out, because OpenStack has changed where their SDK libraries are hosted and we haven't been able to track them down yet.  Also, insofar as the latest hotness to hit Go's package management landscape goes, we've lost the collective will to move to yet-another-vendoring tool.  What we've got works, and we're going to stick to it until the core team deprecates it.

If you'd like to help out with the design and implementation of new demo systems (all most assuredly to be written in Go), we'd love to work with you!
