### ISSUE TITLE
[BUG] Cloud Storage Status Not Affected by Global Storage

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/shield#504]
**Describe the bug**
Global storages are not being counted for the Cloud Storage status on the status bar

**To Reproduce**
1. Have a working normal storage
2. Have a broken cloud storage
3. Look at the status bar

**Expected behavior**
The status should be RED

**Screenshots**
![image](https://user-images.githubusercontent.com/12000017/57099383-51152c80-6cea-11e9-8d9c-2dccf7411396.png)

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.1.0

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Windows
 - Browser: Firefox
 - Version: 66.0.3

**Additional context**

**Comment by jhunt** [comment]
Verified this on latest master, by breaking `CloudStor` in testdev.

<img width="839" alt="Screen Shot 2019-05-14 at 10 00 20 AM" src="https://user-images.githubusercontent.com/20047/57703990-189d1900-762f-11e9-9c01-9bfc1b598cfd.png">

A few things to note:

1. The Cloud Storage detail page has no indication that the system is unhealthy
2. There is no way to view the `test-store` tasks that caused it to flip out of ok state into a non-ok state.

**Comment by jhunt** [comment]
It occurs to me this morning that the HUD may only be considering the _active_ storage systems; I checked that, and that is definitely not the case.  I believe as we look deeper into this issue, we will find that it is just not considering the health of global stores.

This brings up an interesting question:

> Should Tenants see a bunch of red for something outside their control. which they themselves cannot cause.

On the plus side, it's nice to know that something is broken.  It provides more impetus to the site operators to fix it, since more people will see it.  It also means that tenants know that things might be broken with their backups.

On the minus side, I may not care about the shared storage.  If I'm not using it, should I be notified if it is broken?  The flipside of that is that if I do happen to select a broken cloud storage system, my HUD will then become red to show that new brokenness exists, when it is not in fact new.

I think the best course of action is the original suggestion: just include all storage _accessible_ to a tenant in their HUD.  Then we ought to document a "No Broken Windows" stance on the HUD.
